export const SEED_DATA = [
  {
    date: 'Dec 15, 2018',
    description: 'Shake Shack is an American fast casual restaurant chain based in New York City. It started out as a hot dog cart inside Madison Square Park in 2001.Hot town, Shack in the city! Our first-ever Dallas Shack is located in Uptown’s 11-acre office and retail complex, The Crescent. The Dallas Uptown Shack is located under a verdant canopy of trees, the perfect spot to kick back with a delicious ShackBurger and local beer, just steps from a corner park complete with lawn furniture and bocce ball. In addition to the Shack classics, the menu features the Dallas-exclusive Link Burger, a cheeseburger topped with griddled Pecan Lodge jalapeño cheese sausage link, pickles and ShackSauce.',
    offer: '??% off any meal',
    title: 'Shake Shack',
    address: '2500 N Pearl Street, Dallas, TX 75201',
  },
  {
    date: 'Dec 15, 2018',
    description: 'Get the best pet supplies online and in store! PetSmart offers quality products and accessories for a healthier, happier pet. This coupon is valid when you buy any bag of food at PetSmart. PetSmart Inc. is an American retail chain operating in the United States, Canada, and Puerto Rico that is engaged in the sale of pet animal products and services such as dog grooming and dog training, cat and dog boarding facilities, and daycare.',
    offer: '??% off any pet food',
    title: 'PetSmart',
    address: 'Any location',
  },
  {
    date: 'Dec 25, 2018',
    description: `Shop the latest trends in home decor at Urban Outfitters. You'll find unique and stylish home accessories, room furnishings + more to deck out your place. Urban Outfitters, Inc. is an American multinational lifestyle retail corporation headquartered in Philadelphia, Pennsylvania. It operates in the United States, Sweden, United Kingdom, Spain, Denmark, France, Germany, Ireland, Belgium, Canada, Italy, the Netherlands, Israel and Pakistan.`,
    offer: '??% off any UO home items',
    title: 'Urban Outfitters',
    address: 'Any location',
  },
  {
    date: 'Dec 20, 2018',
    description: `Shop the latest trends in Target. You'll find unique and stylish clothings, accessories, shoes + more. Target Corporation is the second-largest department store retailer in the United States, behind Walmart, and is a component of the S&P 500 Index.`,
    offer: '??% off any dress',
    title: 'Target',
    address: 'Any location',
  },
  {
    date: 'Dec 22, 2018',
    description: 'Frappuccino is a trademarked brand of the Starbucks Corporation for a line of iced, blended coffee drinks. It consists of coffee or crème base, blended with ice and other various ingredients, usually topped with whipped cream and sauces.',
    offer: '??% off any frappuccino',
    title: 'Starbucks',
    address: 'Any location',
  },
  {
    date: 'Jan 01, 2018',
    description: 'Christmas is around the corner. Shop Christmas tree, ornaments, candles and more at Home Depot! Enjoy the coupon.',
    offer: '??% off any holiday decor',
    title: 'Home Depot',
    address: 'Any location',
  },
  {
    date: 'Dec 31, 2018',
    description: 'Lisa Says Gah is an independent boutique and blog Focused on connecting you with truly special pieces, we partner with designers that are mindful of ethical manufacturing.',
    offer: '??% off any dress',
    title: 'Lisa Says Gah',
    address: 'Any location',
  },
  {
    date: 'Dec 31, 2018',
    description: 'Come enjoy a ramen noodle soup at Ramen Ren. It’s delicious!',
    offer: '??% off any noodle soup',
    title: 'Ramen Ren',
    address: 'Any location',
  },
  {
    date: 'Dec 28, 2018',
    description: 'Shop the Dyson Airwrap™ hair styler. Engineered to curl, smooth and dry hair. A hair curler without heat.',
    offer: '??% off any Dyson hair product',
    title: 'Dyson',
    address: 'Any BestBuy',
  },
  {
    date: 'Dec 31, 2018',
    description: 'Stock up on makeups, skincare products, tools at Sephora this holiday season!',
    offer: '??% off any $100 purchase',
    title: 'Sephora',
    address: 'Any Location',
  },
  {
    date: 'Dec 31, 2018',
    description: 'Shop Your Style With Nike Shoes for Running, Training, Basketball & More. Free 30-Day Returns. Free Shipping For Members. Types: Air Force 1, Cortez, Metcon, Air Max, Pegasus, VaporMax, Mercurial, Free, Epic React.',
    offer: '??% off any $300 purchase',
    title: 'Nike',
    address: 'Any Nike store',
  },
]
